export enum MUSIC_ACTION_TYPES {
  FETCH_MUSIC_DATA_START = "FETCH_MUSIC_DATA_START",
  FETCH_MUSIC_DATA_SUCCESS= "FETCH_MUSIC_DATA_SUCCESS",
  FETCH_MUSIC_DATA_FAILED= "FETCH_MUSIC_DATA_FAILED",
  SET_TOP_CHART_ALBUMS = "SET_TOP_CHART_ALBUMS",
  SET_COMPLETE_MUSIC_DATA = "SET_COMPLETE_MUSIC_DATA",
  ALBUM_CURRENTLY_BEEN_VIEWED ="ALBUM_CURRENTLY_BEEN_VIEWED",
  PLAYING_SONG_INDEX = "PLAYING_SONG_INDEX",
  PLAYING_SONG_ARRAY = "PLAYING_SONG_ARRAY",
}
